[package]
name = "haplotype_phaser"
version = "0.1.0"
authors = ["jim <jimshawster@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
time = "*"
fxhash="*"
statrs="*"
permute="*"

[profile.release]
opt-level = 3

[profile.dev]
opt-level = 3
